### ISSUE TITLE
[Feature request] build static

### ISSUE THREAD

**Issue by frankycalo** [babelouest/glewlwyd#111]
Hi Nicolas Mora,
very very good job.

I wanted to ask you if you can compile glewlwyd in static mode including the orcania, yder, hoel, and ulfius libraries, in order to make it easier to distribute the application.

Thanks for your attention and greetings from Italy.
Francesco Calò

**Comment by babelouest** [comment]
Hello,

Thanks for the support!
Currently Glewlwyd is compiles in shared mode because it's easier to build and to maintain. Lately when I tried to build it or its dependencies in static mode I had a few problems so I dropped the idea. Could you describe the use case to help me understand why you need it in static mode? You already have the docker image or the distrib ppackages, could it be sufficient?

**Comment by frankycalo** [comment]
Hi,
ok thanks for the reply.
