### ISSUE TITLE
[Feature request] Allow some OS signals to manage glewlwyd service

### ISSUE THREAD

**Issue by a1730** [babelouest/glewlwyd#116]
**Is your feature request related to a problem? Please describe.**
We run glewlwyd under [runit](http://smarden.org/runit/runsv.8.html) Linux supervision and manage our services via OS signals.
Would like for  glewlwyd to leave some signals for external process supervision and management. 

**Describe the solution you'd like**
Ideally we would like glewlwyd to leave HUP(1), INT(2), QUIT(3), TERM(15) to the external supervisor. It is okay to handle and re-throw but not swallow these signals. I am not a C programmer but it looks like the signals are being swallowed [here.](https://github.com/babelouest/glewlwyd/blob/2a1fba05cee6426e2107de4c76d4aacf25ee9436/src/glewlwyd.c#L188-L195)

**Describe alternatives you've considered**
We run glewlywd with 'nobody' user id so we need someone with root privilege to kill the program if we need to perform changes to the config, or need it to come down for whatever reason. 

**Additional context**
Our admins would not appreciate glewlwyd if woken in the middle of the night because users cannot log in.
Our admins are currently suspicious of glewlwyd because it can do whatever it wants without supervision. We use [runit's chpst](http://smarden.org/runit/chpst.8.html) to change -manage- process state including user id under which the service running, and to manage max memory available to our processes. However, glewlwyd seems to be **escaping** its bounds.
No, kill -9, is not used around here because it can leave services in unknown state.
We will rather not adopt the application if kill -9 is the only avenue to terminate its process **or** if it needs manual intervention coupled with elevated privilege for management.

**Comment by a1730** [comment]
Looks like a false alarm. Our bad. We needed to create AppArmor rules to allow the supervisor to  teminate glewlwyd . This issue is resolved. Apologies for the false alarm.

**Comment by babelouest** [comment]
I'm glad you found out a solution because I wouldn't know how to handle this feature request otherwise.

Indeed Glewlwyd intercepts standard signals but it's to allow cleaning up its state, the memory allocated and properly close the opened sessions (database, oath, etc.).

Glewlwyd is designed like that because I didn't want to implement a shell or to allow REST APIs to control start/stop/reload commands, too dangerous and overkill. Its config file doesn't have to be changed every other morning and Glewlwyd startup is very quick (~1 second in my environment which isn't a big server, far from it).

Happy hacking @a1730 !
