### ISSUE TITLE
[Feature request] Reset forgotten password

### ISSUE THREAD

**Issue by yrammos** [babelouest/glewlwyd#130]
**Is your feature request related to a problem? Please describe.**
"I forgot my password" link on the login form.

**Describe the solution you'd like**
Unless I'm missing something, there is no way for a user to request a password reset if the credential is forgotten.

**Describe alternatives you've considered**
I considered instantiating a "email password" authentication scheme, which would presumably allow the user to enter the profile app, but the password change form would still require the old (lost) password.

**Comment by babelouest** [comment]
Hello @yrammos ,

Of course it's a feature I have thought of, it was possible in Glewlwyd 1.x but the feature wasn't reproduced in Glewlwyd 2.x because there are design issues that must be resolved before.

In practice, a plugin similar to the register plugin can be made to achieve this feature.

The main problem is that in Glewlwyd 2, the password isn't the only way for a user to authenticate. In fact, it may be possible for users not to use passwords at all, Users can authenticate via OTP, Webauthn or TLS certificates as unique auth factor.

A smaller issue is that an e-mail address isn't mandatory.

So first I must enlarge the `Reset forgotten password` feature to `Lost authentication`, like when a user has lost its password or its yubikey and can't access the profile page.

Then, the e-mail sent may not be the only way to use. I've seen for example in Gitlab that they generate a set of GUID when a user enables 2-factor authentication. The GUID can be used when the user lost its password and/or 2nd factor authentication.

What I mean is that sending an e-mail to reset a user password is possible, but it mustn't be the only way for a user to change its authentication factors. The attack vectors based on an e-mail or the password are multiple. Therefore the `reset password` may become a weak link in Glewlwyd's security design.

But again, I totally agree with the idea!

**Comment by yrammos** [comment]
(As far as I can tell, admin users are not able to change a user's password via the "delegate" function. So users losing their credential would need to either be deleted or reset via MySQL.)

**Comment by babelouest** [comment]
In the admin page,m when you create or update a user, you can change its password in the modal:

![update user](https://github.com/babelouest/glewlwyd/raw/master/docs/screenshots/user-new-property.png)

**Comment by yrammos** [comment]
Duh! Thanks, @babelouest. I knew I was missing something.

Might the following password reset strategy be workable?

* IF the user has an email on record AND NO additional authentication factors => provide a "lost authentication credentials" link on the login screen.
   * Clicking on that would provide the user with a randomly generated temporary password via email.
* IF the user does *not* have an email on record OR has at least one non-email authentication factor enabled, the "lost authentication credentials" link would display a localized message with the admin's contact information for assistance.

Might this strike a reasonable balance of security and usability?

**Comment by yrammos** [comment]
@babelouest which of the two "if's" is the prohibitive one? The second one ("contact the admin") may indeed be a hassle for the admin, but it is currently the only option available. The first one, however, seems to me entirely reasonable. A user registering for an internet service on the basis of an email/password pair fully understands, I believe, that their security depends on the security of their email account—otherwise they enable a second factor. I can imagine customers being *very* angry if they forget their password at 2am and an administrator is not available to help them on the spot!

**Comment by babelouest** [comment]
@yrammos , the big `IF` is the first one.

I can imagine a service where the users' e-mails are considered weak, therefore using the e-mail to authenticate the user for account recovery is weak, therefore Glewlwyd users' accounts are weak.

Like I said, your use case is the most common use case nowadays, but passwords and e-mails tend to disappear, or at least to be considered less secure than they use to be.

That's why I consider this feature is more complicated than it seems, and I want to implement as secured as I can.

For example, a strong account may need for recovery an e-mail sent (when the e-mail is verified), and/or the use of a 2nd factor like OTP or webauthn, and/or a previously given recovery code.

**Comment by yrammos** [comment]
Thanks for the detailed assessment, @babelouest. Beyond doubt this would be a fabulous plugin. Meanwhile I'll be keeping a beeper on my bedside table for those 2am password reset calls :)
