### ISSUE TITLE
[Question] Optional authentication factors possible?

### ISSUE THREAD

**Issue by yrammos** [babelouest/glewlwyd#131]
Wisely enough, glewlwyd makes provision for non-mandatory authentication factors in its user registration workflow.

Is it possible to assign optional authentication factors to a *scopes*, as well? I'd like users with TOTP tokens to be prompted for a single-use code, but those without such tokens to still be able to log into the same scope.

Conceptually, such a configuration could be formulated as the conjunction of two authentication scheme groups: one with TOTP and an *empty* (password-only) group.

Thanks as ever, @babelouest

**Comment by babelouest** [comment]
One way to achieve this is to use the schemes OTP and [retype password scheme](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#retype-password-scheme) and disable password authentication in the scope.

Then you can follow the [non password authentication](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#non-password-authentication) documentation to complete it.

This way the user must use password or OTP to authenticate.

**Comment by yrammos** [comment]
Excellent! The retype password scheme had escaped me. Thank you.

**Comment by yrammos** [comment]
@babelouest my apologies for reopening this; I may have been unclear. The intention is to provide the following two authorization paths:

Password + TOTP

OR

Password

My understanding is that this is not currently possible. Would it become possible if I created an authorization scheme that would be "always true" (without the user's intervention)? Then password authentication would be left enabled for the scope, and I'd have one additional scheme for each scenario.

**Comment by babelouest** [comment]
One way to achieve this may look like that, but with a limitation that I'll explain:

- You create 2 scopes: `scope1` and `scope2`. `scope1` requires password authentication only, `scope2` requires password authentication and scheme OTP.
- Users that have OTP scheme must have all scopes available
- Users that don't have OTP scheme must have only `scope1`

Therefore the admin must manually add `scope2` to the list of scopes of users that have OTP scheme.

Then when the OAuth2 client will access Glewlwyd, the scopes list must be: `scope_list=scope1+scope2`

When the user logs in, if she/he has scope2 available, the OTP code will be required, if she/he doesn't have scope2 available, the OTP code will not be asked, only the password.

If a user has `scope2` but hasn't registered an OTP scheme, she/he will have the following error message on login: `You must register a scheme in your profile before using it for connection`, that's why the scope2 should be added manually.

If your users are created via the registration plugin, you can set the OTP scheme mandatory during registration.

The reason Glewlwyd is designed like this is because I don't want to deal with different levels of secured access for the same resource. I consider that if a scope requires 2 authentication factors, then it must not be possible to access this scope with only one.
