### ISSUE TITLE
[Question]Why not TEXT type in postgres SQL scripts

### ISSUE THREAD

**Issue by a1730** [babelouest/glewlwyd#161]
**Is your feature request related to a problem? Please describe.**
Was wondering why you chose to use varchar(n) type in sql scripts targeted at postgres database. Please notice that TEXT type is used in sqlites3 scripts.

**Describe the solution you'd like**
The use of TEXT type rather than varchar(n) in postgres database scripts.

**Describe alternatives you've considered**
N/A

**Additional context**
Was wondering why you chose to use varchar(n) type in postgresql scripts. Postgres has supported TEXT type going back to [v7](https://www.postgresql.org/docs/7.3/datatype-character.html), and it is customary in that world to use TEXT rather than character varying(n) or varchar(n). 
Oh, changing to TEXT type reduces our technical debt on column sizes when you need to change the size of some of the structures. It is one less thing to worry about.

**Comment by babelouest** [comment]
Hello,

The main reason I use `VARCHAR(n)` instead of `TEXT` is to add another layer of security in the data. All `VARCHAR(n)` columns are size limited in the application, like the username, the name of a module, a token hash.

When a column can have accept large value, then the type `TEXT` is used:

```SQL

CREATE TABLE g_user_property (
  gup_id SERIAL PRIMARY KEY,
  gu_id SERIAL,
  gup_name VARCHAR(128) NOT NULL,
  gup_value TEXT DEFAULT NULL, -- This column can store large data
  FOREIGN KEY(gu_id) REFERENCES g_user(gu_id) ON DELETE CASCADE
);
CREATE INDEX i_g_user_property_name ON g_user_property(gup_name);
```

Another reason is because the Postgre tables are based on the MariaDB scripts, and in MariaDB, `TEXT` columns can't be indexed.

But what about SQLite3 `TEXT` columns then? SQLite3 considers `VARCHAR` columns as `TEXT` columns and doesn't enforce the text size, i,.e. you can set a text of 2^32 char in a `VARCHAR(10)` columns without SQLite3 engine [to be mad](https://www.sqlite.org/faq.html#q9).

Eventually I could replace all `VARCHAR` columns with `TEXT` columns in the Postgre database without issues, but by habit and to keep the code cleaner, I prefer not to in this release.

Maybe in a future major release though.

**Comment by babelouest** [comment]
@a1730 , are your satisfied with the answer?

**Comment by a1730** [comment]
Your response makes sense. However, the Postgres db text type is not as limited as the MariaDB implementation. Postgres will gladly index text columns.
Also, unlike sqlite3, Postgres **will** enforce a size constraint on varchar(n) columns hence my previous reference to technical debt. One needs to retest the application when a VARCHAR(n) column changes its size even if *All VARCHAR(n) columns are size limited in the application* since the database has its contact on the said column and the application can still fail at runtime.

Your choice is a perfectly valid engineering choice and we will gladly wait for the future release when glewlwyd leverages Postgres TEXT type. Thank you.

**Comment by babelouest** [comment]
Even if I understand your concern with the retest issues on column size change, the technical debt is very unlikely here because I have no plan to increase the size of the limited columns, lots of application rules and behaviour are based on these fixed sizes.

Also, because of the MariaDB limitation, I'll probably never change the column during a major release lifetime.

But your issue made me understand better the PGSQL data structure so I'll keep in mind for the next release and my other projects, thanks @a1730 !
