### ISSUE TITLE
Redundancy in Glewlwyd

### ISSUE THREAD

**Issue by Andy2903** [babelouest/glewlwyd#168]
Hi,

is there currently the possibility to run multiple instances of Glewlwyd redundant? I know this can be done with docker/kubernetes but i'm wondering if Glewlwyd itself has any features or best practices on that topic.

Thanks!

**Comment by babelouest** [comment]
Hello @Andy2903 ,

I have implemented functionalities for multiple instances in Glewlwyd, but since I don't need those functionalities, they could use some feedback.

The use case I have thought of is to use Glewlwyd in a load balanced network. If you think of other use cases where redundancy is useful, let me know.

You can have multiple instances of Glewlwyd sharing the same database, i.e. the same context for everyone.

The following tests are succesfull:

- Run 2 instances of Glewlwyd from different hosts: glewlwyd1 and glewlwyd2
- Perform a code request from glewlwyd1
- Use this code to get a refresh token and an access token from glewlwyd2
- Refresh the token from glewlwyd1

What must be taken care of is if you add or remove plugins instances or update plugins configuration (user or client backends, schemes and plugins), you must reload all modules on the other glewlwyd instances so they are synchronized.
https://github.com/babelouest/glewlwyd/blob/master/docs/API.md#reload-all-modules

You can automatize this process with an [event log](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#event-logs-triggered) trigger and an access via [API keys](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#access-to-administration-api-via-api-keys)

**Comment by Andy2903** [comment]
Thanks for the useful information.

Yes, I was thinking about the same use case where you have one or more Glewlwyd instances behind a load balancer and all instances are connected to the same database.

How about a feature that Glewlwyd knows the other instances (their ip address, port and a valid API key). Now it would be possible to [reload all modules](https://github.com/babelouest/glewlwyd/blob/master/docs/API.md#reload-all-modules) from the Glewlwyd instance, that was changed. This would require the changing instance to update the other instances every time itself changes an endpoint. For that I see following problems: 
- what happens when one (or more) of the other instances aren't reachable?
- how and more importantly when does the instance that wasn't reachable get the new information? Assuming the reload all modules request didn't reach the instance.

This feature would replace the event log trigger which I think is quiet handy.

I'm no expert at redundancy but therefore I'm sharing my thoughts for others to correct me 🙂

**Comment by babelouest** [comment]
Indeed, implementing a synchronization process between Glewlwyd instances is complex in itself, and it may not fit everyone's need easily, I'm not eager to do this at that time. In a similar topic, I was recently asked to add webhooks in Glewlwyd and came with the same conclusion.

I also considered that using Glewlwyd in load-balanced mode may not happen a lot.
Usually one single user doesn't ask for too much load on the server: a few API requests for the authenticating part, and when a refresh token is provided, an access token is requested every hour or so, depending on the access token lifespan.

I implemented Glewlwyd in C to run smoothly on small machines like a raspberry pi with a small amount of users, so if Glewlwyd is executed on a traditional server with a regular amount of RAM and cores, it should handle the load of multiple users.
That last part is more an extrapolation than a certitude. I don't have glewlwyd running in this kind of environment and I haven't seen Glewlwyd running in environments with gazillion of users. I was once asked if there was performance tests in this issue https://github.com/babelouest/glewlwyd/issues/119 , you can check the results I came with if you're curious.

So instead of adding more complexity and potential security bugs in Glewlwyd, I preferred moving this complexity outside of the core application. That's why I added the event triggers and the API keys.

The way I see it, it's easy to make a small script in Python or Perl or whatever admins are comfortable with, this script would listen to the log output and would run a command when a event is triggered. If you're afraid this script would reduce the performance, you can log Glewlwyd's message using syslog or journald and configure it for remote logging, the execute this script from the log server. That's an example I have in mind, I haven't tested it though.

**Comment by Andy2903** [comment]
As you pointed out Glewlwyd is optimized to be resource friendly. But what I'm also concerned about is the case when a Glewlwyd instance breaks down (Bug in Glewlwyd, Server failure, ...). Then another instance should take over so the service is highly available. 

It would be nice to have a feature built in, but the event logger should run just fine too.

Thanks for your replies!
