### ISSUE TITLE
Not able to start the service

### ISSUE THREAD

**Issue by vipinsingh211** [babelouest/glewlwyd#18]
Sorry to annoy again, after the setup as per the Readme I tried to start the service using below command, which says the service started OK. but in actual the service is not running. I verified on browser as well as using `ps` command.
```linux
$ sudo ./glewlwyd-init start --config-file=glewlwyd.conf
Starting Glewlwyd OK
```
Also, the `start-stop-daemon` was not available for CentOS therefore I am using direct binary of the same. Which I downloaded from a website. Please help in debugging what's going wrong.

**Comment by babelouest** [comment]
Hello,

I don't know about CentOS, so I suggest going through its documentation to make one, not adapting the debian-specific scripts in this repository.
Maybe https://www.google.ca/search?q=centos+create+daemon can help

Also, about your service not running, I'm missing a lot of information to help you. If you run the program from the command-line, you can have some help in the logs.

```shell
$ ./glewlwyd --config-file=glewlwyd.conf
```

In the `glewlwyd.conf` file, don't forget to set the value `log_mode` to at least `console` and the value `log_level` to at least `log_level`, then you can have a better view of the program status.

If glewlwyd is started normally, you should see logs that look like:

```
2017-01-12 21:08:03 - Glewlwyd INFO: Starting Glewlwyd Oauth2 authentication service
2017-01-12 21:08:03 - Glewlwyd INFO: Start glewlwyd on port 4593, prefix: glewlwyd, secure: false
```

If not, the logs output should tell you where your problem is.

Also, I suggest not using sudo to run the program, you don't need to if you leave the default port number, and if you do, you have possible security leaks. If you want to use 80 or 443 as port number, and having glewlwyd accessible from untrusted networks like the internet, I strongly suggest a reverse proxy like in Apache, so there will be another layer of security.

**Comment by babelouest** [comment]
Hi @vipinsingh211 , any updates on this issue?
