### ISSUE TITLE
[Feature request] json log format

### ISSUE THREAD

**Issue by rurus9** [babelouest/glewlwyd#183]
It would be ideal to be able to set json as the log format, so you can put logs to json log parser (e.g. fluentd or logstash have plugins for it). It would be extremely useful when using ELK /EFK stack (Elastic, Fluend|Logstash, Kibana) for log processing.
  
A sample log for issuing a client credential token could look like this:
```
{"level":"info","plugin":"oauth2","flow":"client_credentials","action":"token_issued","scope_list":"SCOPES","client_ip":"IP_ADDRESS"}
```

**Comment by babelouest** [comment]
At the moment, the logs are provided by [yder](https://github.com/babelouest/yder) where the logs are created using a `printf` like format, example:

```C
y_log_message(Y_LOG_LEVEL_DEBUG, "get_access_token_from_refresh oidc - client '%s' is invalid or is not confidential, origin: %s", client_id, ip_source);
```

It's not possible as-is to change the output to a JSON format, it would require to change the logs paradigm.

- Either by adding a new log format in yder:

```C
y_log_json(int log_level, json_t * log_message);
```

- Or by logging a stringified JSON message in addition to the log messages already present:

```C
y_log_message(Y_LOG_LEVEL_DEBUG, "{\"level\":\"info\",\"plugin\":\"oauth2\",\"flow\":\"client_credentials\",\"action\":\"token_issued\",\"scope_list\":\"SCOPES\",\"client_ip\":\"IP_ADDRESS\"}");
```

I think both solution are overkill because they are against glewlwyd's KISS philosophy. Another solution I can think of is for an external program to parse log messages and transform them into the JSON you need.

Unless you think of another suitable solution in between?

**Comment by rurus9** [comment]
Maybe some switch in the glewlwyd configuration, plain logs (default) or json logs (if possible)?

> Or by logging a stringified JSON message in addition to the log messages already present

No, that would only obscure the situation with automatic log processing. If that's problematic (json log), better stick with plain logs.
Greetings

**Comment by babelouest** [comment]
The switch to choose between JSON and passion text logs wouldn't fix the complexity problem.

I'll stick with the plain text logs only for this major version 2.x, but it's keep that in mind when a future version 3.x will be planned.
