### ISSUE TITLE
Changing user scopes removes g_user_password entry

### ISSUE THREAD

**Issue by ajl199** [babelouest/glewlwyd#188]
**Describe the issue**
Adding or removing scopes from a user through the admin web interface results in them being unable to log in until their password is changed by admin. On inspection, what seems to be happening is that when their scopes are changed, their entry in the g_user_password table disappears entirely.

Is it just me this is happening to?

**System (please complete the following information):**
Glewlwyd version 2.4 running from Docker container on AWS Linux 2. MySQL databases.

**Comment by babelouest** [comment]
Hello @ajl199 ,

To complete the bug description:
- are you using the [multiple password](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#multiple-password-authentication) feature?
- what backend are your using to store the users? If you use the database backend, what database type are you using?

**Comment by babelouest** [comment]
No wait, I see it too, let me check what's wrong...

**Comment by ajl199** [comment]
Just came to type a reply and saw your latest. Nonetheless, it's not using multiple password, and is using a database backend: mysql with separate user and config databases, both on AWS RDS.

**Comment by babelouest** [comment]
I think I found the problem and fixed it in https://github.com/babelouest/glewlwyd/commit/ef433b3df5b31ff3a62887fb7dfddbec08a1b8fc
Can you give it a try?

**Comment by ajl199** [comment]
Thank you!

I'm a bit debilitated when it comes to building things right now, but can try as soon as I've got the right systems up and running again.

**Comment by babelouest** [comment]
You can build a docker image from source: https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#docker-image-builder

But I don't recommend to use your current database with the last commit because there a few changes in the database: https://github.com/babelouest/glewlwyd/blob/master/docs/database/upgrade-2.6-core.mariadb.sql

And since version 2.6.0 isn't finished yet, there may be other changes in the database before the release.

Until 2.6 is released, if you have other issues to report, I'm all ears!

**Comment by ajl199** [comment]
Typo above now corrected (sorry) I was on version 2.5.4, not 2.4. Got access to a system I could build docker containers on back this morning, have done so and your fix seems to have done the trick. Thank you very much for that speedy turnround.
