### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by rafaelhdr** [babelouest/glewlwyd#19]
Hello,

Do you think in build this as a docker image? If you need, i would appreciate to help you on this.

If you don't know Docker, it would make very simple to start an instance with a single command (`docker run babelouest/glewlwyd`, and then is just curl). Here is an example of oauth2 server on docker: https://hub.docker.com/r/gisjedi/go-oauth2-server/

I made one image for testing (because the documentation is based on Debian, so i build from a Docker Debian image), and worked very fine. I was thinking in a configurable docker image, by adding a glewlwyd.conf (or by env vars). A good example is MariaDB docker documentation page: https://hub.docker.com/_/mariadb/

Do you think is a good idea? Have any suggestions/recommendations?

*Ps.: Thank you very much for this library. It is awesome.*

**Comment by babelouest** [comment]
Hi Rafael, 

Having a docker image would be awesome! I know about docker but I never used it, mostly because I don't need it in my nano computers configuration.
But I know the advantages of using docker and I'm sure glewlwyd would be a perfect candidate for this kind of use.

I would be glad if you could help me providing a glewlwyd image.

I don't know how configurable a docker image is, so I don't know if you must provide a generic image, then deploy it with a glewlwyd.conf , or if an image must have its configuration written in the stone. I'm asking because you can choose between mysql or sqlite3 as dB backend, and also between ldap, database or both backends as authentication storage. Is it better to provide multiple images? Maybe you can help me understand that? 

The documentation is based on Debian because it's my favorite Linux distribution, but I think it can be quite system agnostic since all its components are pretty portable, at least on other Linux systems. So I leave it to your judgment.

Thanks for offering to help!

**Comment by rafaelhdr** [comment]
Ok, let's do it :)

About the configuration, we can provide multiple images using tags (1.0-mysql, 1.0-sqlite, 1.0-ldap-mysql...), and then we can run with something like this: `docker run -v $PWD/myconfig:/var/config babelouest/glewlwyd:1.0-mysql`. In this case, the user would say to use an image with MySQL, and provide a glewlwyd.conf file, where he could define information for accessing the MySQL database.

I like Debian, too. But a good option (for Docker) is to have also Alpine (another tag, like babelouest/glewlwyd:1.0-mysql-alpine). It is an very small distribution, so a lot of people like it on docker.

I will do a basic image ASAP (probably until this weekend). So, i think will be easier to understand it :)

**Comment by babelouest** [comment]
That's great, thanks a lot!

**Comment by rafaelhdr** [comment]
Hello,

Just made an image (but i still have work to do): https://github.com/rafaelhdr/glewlwyd-oauth2-server

What do you think?

I am still thinking about the following tasks:

- Quickstart for mysql
- Quickstart for ldap
- Different build for mysql/sqlite/ldap (today, i install everything, but i think it is not necessary to apt-get install sqlite3 on mysql tagged image)
- Images with alpine linux
- Custom build with environment variables
- Check [best practises](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/) (i am still learning)
- Automate deploy images (webhook from github)
-  Transfer the github project repository to you (you are the owner, i am just contributing)

**Comment by babelouest** [comment]
Hello @rafaelhdr ,

This looks pretty cool, thanks a lot. I've read the [Dockerfile](https://github.com/rafaelhdr/glewlwyd-oauth2-server/blob/master/Dockerfile) and I have some suggestions and questions. I don't know Docker so if I'm wrong, don't hesitate to correct me.

First, in the last weeks, I've updated the underlying frameworks and libraries Glewlwyd is based on, like [Ulfius](https://github.com/babelouest/ulfius/tree/2.0b) and [Hoel](https://github.com/babelouest/hoel/tree/2.0). There is no real change in Glewlwyd itself but the APIs were modified, so an update is mandatory if we update the libraries. It's still in beta mode but all my unit tests are now valid and I'm already using it with success so far. If you're willing to test it, that would be cool! :)

Second, this is kinda related, I suggest to specify in the dockerfile the release number or the commit id in the `git clone` commands. Then it will be safer for users, the last commit of each repository may be incompatible or generate undefined bugs. By fixing the release number of each piece, we will be sure every user will have the same program running.

There comes my third point, kinda related too ;). Is it possible to download binaries instead of the source code? It will be safer for docker not to have a whole bunch of development tools not needed in production mode I think. Maybe we could host the binaries in this repository, assuming that the system running the docker images will always have the same architecture, or a compatible one of course.

Concerning mariadb or sqlite, I can make a small change in the program to make it mariadb only or sqlite only if necessary, then it's easy to make 2 dockers, one for mariadb and one for sqlite. The sqlite image can work out of the box, while the mariadb one will need for the user to specify the location of the database in the `glewlwyd.conf` file.

Concerning LDAP setup, I don't know how to make a quickstart for it, except with a documentation. A LDAP base is usually specific for each organization, so the `glewlwyd.conf` file will need specific entries anyway. Do you have some suggestions?

Also, about the `jwt` configuration, there are 2 modes for `jwt` signatures, rsa or sha, each of them require a secret kept by the owner of the application. We must make the user choose its mode before or during the installation, otherwise, using a default certificate or secret will be like having no security at all... :)

Finally, we need to make a sql file to properly initialize the database with an admin user and a client to administrate it. This is explained in the documentation but we need to make some steps more standalone. If the database is Mariadb, no problem. But if the databse is Sqlite, we must choose a hash algorithm that will be the chosen one, because every hash signatures for sessions, tokens and signatures will use it, and since the application must be initialized with data, we can't easily change it afterwards:
https://github.com/rafaelhdr/glewlwyd-oauth2-server/blob/master/glewlwyd.conf#L136

**Comment by rafaelhdr** [comment]
Hello @babelouest ,

> First, in the last weeks, I've updated the underlying frameworks and libraries Glewlwyd is based on, like Ulfius and Hoel. There is no real change in Glewlwyd itself but the APIs were modified, so an update is mandatory if we update the libraries. It's still in beta mode but all my unit tests are now valid and I'm already using it with success so far. If you're willing to test it, that would be cool! :)

I will do something for test :)
I still didn't check the tests (i see you have `tests/test-token.html`). I will check how it works, and if possible, add it to Dockerfile.

> Second, this is kinda related, I suggest to specify in the dockerfile the release number or the commit id in the git clone commands. Then it will be safer for users, the last commit of each repository may be incompatible or generate undefined bugs. By fixing the release number of each piece, we will be sure every user will have the same program running.

> There comes my third point, kinda related too ;). Is it possible to download binaries instead of the source code? It will be safer for docker not to have a whole bunch of development tools not needed in production mode I think. Maybe we could host the binaries in this repository, assuming that the system running the docker images will always have the same architecture, or a compatible one of course.

These two points are very important. I will do as you suggested ("download binaries instead of the source code"). I see you have releases on your repositories, so I will use it.

> Concerning mariadb or sqlite, I can make a small change in the program to make it mariadb only or sqlite only if necessary, then it's easy to make 2 dockers, one for mariadb and one for sqlite. The sqlite image can work out of the box, while the mariadb one will need for the user to specify the location of the database in the glewlwyd.conf file.

What change do you think? Because for me, it is excellent. I was thinking in 2 different .conf files (like `glewlwyd.conf.mysql.sample` and `glewlwyd.conf.sqlite.conf`). Sqlite out of the box, and MySQL would need user configuration (user providing `glewlwyd.conf`).

But about this, I have one question. Can we custom the glewlwyd.conf with environment variables?

For example, on Python, i normally have a config.py, and make this:

```
import os
hostname = os.environ.get("DB_HOSTNAME", "DEFAULT_HOSTNAME")
```

If user have provide env var (`docker run -e DB_HOSTNAME=myhost rafaelhdr/glewlwyd-oauth2-server`), hostname would be myhost. Otherwise, would be DEFAULT_HOSTNAME.

> Concerning LDAP setup, I don't know how to make a quickstart for it, except with a documentation. A LDAP base is usually specific for each organization, so the glewlwyd.conf file will need specific entries anyway. Do you have some suggestions?

I really need to study more about LDAP. I've never used one =/
What changes do we need? apt-get and glewlwyd.conf?

> Also, about the jwt configuration, there are 2 modes for jwt signatures, rsa or sha, each of them require a secret kept by the owner of the application. We must make the user choose its mode before or during the installation, otherwise, using a default certificate or secret will be like having no security at all... :)

No problem. Today it uses the same, only for a quickstart. So new users can check how it works. But we tell them to use a custom password. For the certificate, we also need to persist the certificates.

**Comment by gesanderson** [comment]
I am not familiar with the project, but I do have experience with docker. Here are a few of my opinions:

Everything that's config related should be kept outside of the docker image. That includes the sqlite database the SSL certificates. By keeping the database outside of docker you only have a single image that you need to maintain and rebuild instead of 2. Keeping the SSL certificate outside of the image allows users to reuse certificates that they might have already generated and want to keep. It's easy enough to inject a sqlite database or a SSL certificate using volume mounts at runtime (the `-v` option)

However, what you can do to make life easier for your users is install the tools to generate these things in the docker image and explain in a README how to use them.

I would also use configuration files instead of environment variables for configuration. Again, a config file is easy to inject with `-v`. Using environment variables would mean that you either have to modify the project to read them, or write a shell script that would read the variables and generate a config file. What happens if someone uses environment variables and a config file both at the same time  ? Much simpler to just inject a file IMO.

Improvements:

I would add an `EXPOSE` which makes it easier to use the container when linking other containers together or when using orchestration solutions like docker-compose. 

This one isn't strictly necessary: If you really want to manage an sqlite database inside docker, then  consider exposing a `VOLUME` directory in the image and then mounting data volumes inside the container.

**Comment by rafaelhdr** [comment]
@babelouest ,

I've just made a Quickstart for MariaDB. I think will be easier to understand what we can do.

https://github.com/rafaelhdr/glewlwyd-oauth2-server#quickstart-mariadb

You can think of LDAP as an extra service (like MariaDB).

@gesanderson ,

Thank you very much. I appreciate every help here.

> Everything that's config related should be kept outside of the docker image. That includes the sqlite database the SSL certificates. By keeping the database outside of docker you only have a single image that you need to maintain and rebuild instead of 2. Keeping the SSL certificate outside of the image allows users to reuse certificates that they might have already generated and want to keep. It's easy enough to inject a sqlite database or a SSL certificate using volume mounts at runtime (the -v option)

Yes. I am doing this with sqlite (https://github.com/rafaelhdr/glewlwyd-oauth2-server#persisting-sqlite-database). But I forgot about the SSL. It is sharing the same keys at the image (which is a very bad idea). But ASAP I will make the changes. I liked the suggestion for making tools for the users. I will do it.

> I would also use configuration files instead of environment variables for configuration. Again, a config file is easy to inject with -v. Using environment variables would mean that you either have to modify the project to read them, or write a shell script that would read the variables and generate a config file. What happens if someone uses environment variables and a config file both at the same time ? Much simpler to just inject a file IMO.

I don't know many Docker Projects, but one that I liked is sameersbn/docker-gitlab ( https://github.com/sameersbn/docker-gitlab#available-configuration-parameters ), which has a lot of options passed by env vars.
Why don't we make both? So, everyone could choose which one fits better :)

> I would add an EXPOSE which makes it easier to use the container when linking other containers together or when using orchestration solutions like docker-compose.

It already has EXPOSE :)
https://github.com/rafaelhdr/glewlwyd-oauth2-server/blob/master/Dockerfile#L75

**Comment by babelouest** [comment]
@rafaelhdr ,

I made a quick test today, I didn't know docker was available on Raspbian :)
If I follow your instructions, I can't install glewlwyd docker image because `Unable to find image 'rafaelhdr/glewlwyd-oauth2-server' locally`. I figured it couldn't work out of the box, but for a docker beginner, what are the pre requisites for the docker command to work?

Concerning @gesanderson 's message (thanks a lot for your feedback BTW), what do you think of a generic docker image that will need at least a `glewlwyd.conf` file, and if necessary other files, like certificate files (https and/or jwt) or sqlite db file. The container documentation would explain how to initialize the config, then inject the file(s). It's not full automatic, but if the user needs to redeploy the container, he already has the config files.

@gesanderson , what is the best practice between a pre-compiled program and source code that need to be compile when the container is installed?

**Comment by rafaelhdr** [comment]
@babelouest 

Does it works if you do `rafaelhdr/glewlwyd-oauth2-server:latest` ?
I was nothing tagging as :latest (the default). So, I added this tag now on push. I hope it works now.

**Comment by rafaelhdr** [comment]
@babelouest 

At Dockerfile, now it is downloading release, instead of git clone all of them. Except for Orcania and Yder. I didn't found releases for there 2 repositories.

**Comment by rafaelhdr** [comment]
@babelouest I need your help.

I am trying to make an automated test before the build. But it raises **Error 2**.

```sh
root@298a8a7719c6:/glewlwyd# make test
cd ./tests && make test
make[1]: Entering directory '/glewlwyd/tests'
gcc -Wall -D_REENTRANT -DDEBUG -g -O0 glewlwyd_resource_owner_pwd_cred.c unit-tests.o -o glewlwyd_resource_owner_pwd_cred -lc -lulfius -lorcania -ljansson -lyder -lcheck -lpthread -lm -lrt -lsubunit
glewlwyd_resource_owner_pwd_cred.c:9:19: fatal error: check.h: No such file or directory
 #include <check.h>
                   ^
compilation terminated.
Makefile:65: recipe for target 'glewlwyd_resource_owner_pwd_cred' failed
make[1]: *** [glewlwyd_resource_owner_pwd_cred] Error 1
make[1]: Leaving directory '/glewlwyd/tests'
Makefile:41: recipe for target 'test' failed
make: *** [test] Error 2
```

I tried `find ./ -name check.h`, but no results. What can I do?

**Comment by babelouest** [comment]
Hi @rafaelhdr ,

`check.h` is part of the check framework for glewlwyd unit testing. It's useful for glewlwyd development process but not required to build a release. For the docker image, you should just run:

```shell
$ make
$ make install
```

If you want to run the unit tests, you must install the [check framework](https://libcheck.github.io/check/). On Debian, run `sudo apt-get install check`.

I'll have some time this week-end to test your docker image. I'll let you know. Thanks for your help.

**Comment by rafaelhdr** [comment]
Hi @babelouest ,

I can do the tests, without including them in the project (build a base image, make test, if no error, revert to the base and build). But you are right. Using releases, the tests will be done at this repository. We don't need to test again at the Docker.

Ok :)
At Saturday I will not be available, but I will try to work harder on Sunday.

**Comment by babelouest** [comment]
Also considering that to run the tests you must run glewlwyd with a test base first, then run `make test` then check the results in the console, this is way too manual and overkill for installing a docker image i think:)

No rush for Sunday though I think the docker image will be ready when it will be ready ;)

**Comment by babelouest** [comment]
Hi @rafaelhdr ,

I've just tested the docker image and I must say I'm impressed, I simply ran the command:
```
$ sudo docker run --rm -it -p 4593:4593 rafaelhdr/glewlwyd-oauth2-server
```
And ten seconds later I had an up and running glewlwyd instance ready to work. Awesome job!

Right now I'm working with benmcollins, the developper of libjwt, to [use GnuTLS instead of OpenSSL](https://github.com/benmcollins/libjwt/pull/45).
That way, we can get rid of openssl and have only one security library instead of two.

I also made small adjustments to Ulfius and Glewlwyd in the last releases. When the libjwt pull request will be accepted, we will have a docker image with a smaller footprint therefore more efficient.

Meanwhile, I will send a pull request for some small improvements.

**Comment by rafaelhdr** [comment]
Thank you very much :)

I've just accepted. Just make a comment about the log.

**Comment by babelouest** [comment]
I suggest we close this issue and continue directly in your repository.
This will be more simple and we can handle one problem at a time. Do you agree?

**Comment by rafaelhdr** [comment]
That is a good idea :)
I will do it now. Thank you for helping me.

But do you want to be the owner of the repository? I think it is fair (if not now, later).

**Comment by babelouest** [comment]
For now, you can invite me as collaborator for your repository: https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/
That way I will be able to push directly but you're still the owner. It's your project, I'm helping you with it :)

When it will be ready enough, I will referring your project or the Docker file in Glewlwyd documentation.

If one day you don't want to work on this project anymore, then you can give me the ownership, but in the mean time, I'd rather have you as the owner.

**Comment by rafaelhdr** [comment]
Thank you very much :)
Just added you as a collaborator.

If anyone else come to here, go to [glewlwyd-oauth2-server](https://github.com/rafaelhdr/glewlwyd-oauth2-server), or to [glewlwyd-oauth2-server Issues](https://github.com/rafaelhdr/glewlwyd-oauth2-server/issues)
