### ISSUE TITLE
Wordpress + glewlwyd

### ISSUE THREAD

**Issue by vampiebar** [babelouest/glewlwyd#208]
Hello,
When I setup wordpress and glewlwyd it is giving me error after login

"You must register a scheme in your profile before using it for connection"

![Screen Shot 2022-08-26 at 00 08 19](https://user-images.githubusercontent.com/1489223/186770140-36e51de6-a49a-4479-af3d-6f480e67fda9.png)

What can cause this error?

**Comment by babelouest** [comment]
Hello,

You have this message because you attempt to log in with a scheme like TOTP or Webauthn, but the scheme isn't registered for the user.

The user `Robert` must go into its profile page and register the required schemes for this login. You should read the [user documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/USER.md) for more explanation.

I will add a more obvious link to the profile page when you get this message.
