### ISSUE TITLE
missing ldap auth property in conf file (confidential_property_client_read)

### ISSUE THREAD

**Issue by YogiS** [babelouest/glewlwyd#21]
Trying to bring up an instance I'm seeing the following:

$ sudo /usr/local/bin/glewlwyd --config-file=/etc/glewlwyd/glewlwyd.conf
Error, auth ldap error parameters
Error config file

The following check seems to be failing in file glewlwyd.c:
cur_auth_ldap_confidential_property_client_read != NULL

config_setting_lookup_string(auth, "confidential_property_client_read", &cur_auth_ldap_confidential_property_client_read);

I'd add that in the config but not sure what the RHS value should be.

**Comment by babelouest** [comment]
Hello,

My bad, I forgot about 2 parameters in the glewlwyd.conf.sample in the `authentication` block:
```
confidential_property_client_read = "employeeType"
confidential_property_client_write = "employeeType"
```

They are used to store the `confidential` flag for the clients. Since there is no ldap parameter that could fit this usage, I use the ldap pareter `employeeType` to store this value, since this is unused in my ldap database.

Thanks for the bug report, I'll push a fix asap.
