### ISSUE TITLE
LDAP group mapping

### ISSUE THREAD

**Issue by warroyo** [babelouest/glewlwyd#26]
is there a way to map LDAP groups to certain scopes? I cant seem to find any info on if that is possible or how to do it?

**Comment by babelouest** [comment]
I don't think the answer is yes but I'd like to be sure of your needs, if I add this feature in a future release.

An LDAP database is considered as a flat list of users in Glewlwyd, with the `base_search_user` parameter as the root directory and a subtree search parameter.
To manage the scopes for these users, you need a LDAP property to store them, the default property used is `o` but you can use other properties if you need, but that's basically the leverage you have.

LDAP groups are not handled by Glewlwyd as is, except if the group property is present in the user LDAP entry.

Does that answer your question?
Also, for my understanding, can you explain how you use LDAP groups and how you would like them to be handled by Glewlwyd?

**Comment by warroyo** [comment]
it looks like you actually answered another question I had as well. I was curious about the write access to LDAP and from your response, the LDAP backend does require write access. 

As far as what I would like to be able to do. I would like to be able to connect up LDAP as a user backend and be able to map scopes to LDAP groups. so that i do not need to assign individual scopes to every user. I could say LDAP group "Admins" can have these three scopes for example. so whenever a user is added to the group they automatically have access to the scopes necessary. Also i would like to be able to return the user's LDAP groups inside of the JWT. is this currently possible? 

AS for the write access to LDAP, I work in a large organization and write access to LDAP is just not an option. is there a way to use LDAP without write access? maybe be able to store the scopes in the database and have a mapping to users/groups?

does this answer your questions and give you a better idea of my use case?

**Comment by babelouest** [comment]
Yes, the write access to LDAP is possible, but not mandatory, either for users and clients: https://github.com/babelouest/glewlwyd/blob/master/glewlwyd.conf.sample#L175
So if you administrate your LDAP database with your own tools, Glewlwyd can be a simple client of your LDAP, without write access, but the scope must be set in the LDAP for each users with the property set, otherwise it would have been too overkill and complicated to use both LDAP and database for the same set of users.

Although, as is, you can't add more information in the JWT, it just contains the username and the scope list. A workaround would be to add the group name as a scope for example.

**Comment by warroyo** [comment]
ok that makes sense, would it be possible to have a feature added to be able to pull in custom attributes from ldap to include in the JWT?

**Comment by babelouest** [comment]
That's possible, but the difficulty will be to make it agnostic.
Is can be something like having a new set of entries in the ldap config:
```
user_additional_jwt_property_name = "group"
user_additional_jwt_property_value = "guid" # will fill the jwt property `group` with the content of the LDAP property `guid`
```

Although, linking the users with their LDAP group is not as easy as it sounds, because it would require a new LDAP search query for every user LDAP query.

Maybe in a future release, I'll add the possibility to add authentication backends as plugins, so it will be possible to develop specific connectors and remove the difficulty to have agnostic features.

**Comment by warroyo** [comment]
i think just adding the ability to pass any ldap attribute as you specified about would work for my use case. since each user has an attribute "member_of" in LDAP it would return a list of their groups into the JWT. Clients could then use those groups for authorization in their apps rather than using scopes. I know its not how Oauth is supposed to be used since it wouldn't leverage any scopes however it would be a workaround.

**Comment by babelouest** [comment]
Sure, I was thinking in a near and less near future for new features... ;)

I'll add the specific LDAP attribute in a next minor release (i.e. Glewlwyd 1.3), and the plugins in a future major release (i.e. Glewlwyd 2.0)

**Comment by warroyo** [comment]
sounds great! thank you!

**Comment by babelouest** [comment]
Hello @warroyo ,

Could you try the branch [additional-value](https://github.com/babelouest/glewlwyd/tree/additional-value) for your requirements?

You need to setup the property name in the config file as in the sample: https://github.com/babelouest/glewlwyd/blob/additional-value/glewlwyd.conf.sample#L105

Then, for the LDAP backend, set the additional property value read in the LDAP section: https://github.com/babelouest/glewlwyd/blob/additional-value/glewlwyd.conf.sample#L177
You can also set the write property name: https://github.com/babelouest/glewlwyd/blob/additional-value/glewlwyd.conf.sample#L184
I know you like your LDAP in read-only mode, I'm not offended ;)

If everything's ok, a new JSON property will appear in your access tokens, with the property name as the `additional_property_name` config field, and the value as given in the LDAP property `additional_property_value_read` or the database new field. e.g.: `"new_property":"new property value"`.

The front-end hasn't been modified yet but in your use case this shouldn't be a problem.

Let me know if you have questions or feedbacks, because this is still in development.

**Comment by babelouest** [comment]
Before testing the new branch, you should reinstall the database though.

**Comment by babelouest** [comment]
@warroyo , any feedback on the branch?

**Comment by warroyo** [comment]
@babelouest sorry I haven't gotten any time to try it out yet. thank you for getting that added so quickly. I will hopefully have some time to give it a try this weekend or early next week.

**Comment by babelouest** [comment]
@warroyo , any feedback on the branch?

**Comment by babelouest** [comment]
@warroyo , I've merged the branch since it passed all the tests I added, if you still use want to use this new feature, you can open new issues if you see any more problems.
