### ISSUE TITLE
401 on /api/profile

### ISSUE THREAD

**Issue by Radiergummi** [babelouest/glewlwyd#41]
When requesting `/api/profile` with a valid token, I get a `401` response without a body. The log file does not show an entry for the failed request, like it would for `/api/token`.  
I tried this without any JS complexity, straight with curl:

```shell
$ curl 'https://auth.db.sevigne.de/api/profile' -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHBpcmVzX2luIjozNjAwLCJpYXQiOjE1MjQ2NTQxNzUsIm5ld19wcm9wZXJ0eSI6ImZvbyIsInNhbHqiOiJEXCIqUXYkZWJkOTltISZvVSIsInNjb3BlIjoibG9naW4iLCJ0eXBlIjoiYWNjZXNzX3Rva2VuIiwidXNlcm5hbWUiOiJ0ZXN0In0.-Q4h_yzB11BS0JUTL3eHM--_E0HGhjg1U8CdWQq0XVa094rTYKcfaF2oeDBJZz6EIlceIKqi64KhtFQe8a6OkA' -i
HTTP/2 401 
server: nginx/1.13.6
date: Wed, 25 Apr 2018 11:05:44 GMT
content-length: 0
pragma: no-cache
cache-control: no-store
access-control-allow-credentials: true
access-control-allow-origin: *
```

According to [API.md#profile-api](https://github.com/babelouest/glewlwyd/blob/master/docs/API.md#profile-api), this should work as above.  
The user has the scope `g_profile` set. Is there anything else I'm missing?

**Comment by babelouest** [comment]
I don't know how you got your token but it's not valid. The payload part is the following:
```
eyJleHBpcmVzX2luIjozNjAwLCJpYXQiOjE1MjQ2NTQxNzUsIm5ld19wcm9wZXJ0eSI6ImZvbyIsInNhbHqiOiJEXCIqUXYkZWJkOTltISZvVSIsInNjb3BlIjoibG9naW4iLCJ0eXBlIjoiYWNjZXNzX3Rva2VuIiwidXNlcm5hbWUiOiJ0ZXN0In0
```

If you decode it in base 64, you get the following string:
```javascript
{"expires_in":3600,"iat":1524654175,"new_property":"foo","salz:"D\"*Qv$ebd99m!&oU","scope":"login","type":"access_token","username":"test"}
```

Which looks like a json but it's not, you have a missing `"` after the string `salz` to have a valid json key, also the key is `"salt"`, but eventually, your scope is `"scope":"login"`, where ta valid scope would be `"scope":"g_profile"`, so it wouldn't work anyway.

You can use the file [test-token](https://github.com/babelouest/glewlwyd/blob/master/test/test-token.html) to help you generate access_token. You may have to change the dropdown lists values to fit your needs though.

**Comment by Radiergummi** [comment]
I know it is invalid because I swapped a character before posting it on Github - just to be sure. Seems like I was off by three letters 😄   
However the second part of your answer helps me a lot! `login` is the scope I used while logging in. Does that mean I need to provide all scopes relevant for my future uses while obtaining my token? I was under the impression I'd just assign scopes to the user in Glewlwyd, receiving a JWT with all available scopes.  
Nevertheless, thank you, I know how to handle this now.

**Comment by babelouest** [comment]
In you case, the decoded jwt payload would be something like:
```javascript
{
  "expires_in":3600,
  "iat":1524654175,
  "new_property":"foo",
  "salt":"D\"*Qv$ebd99m!&oU",
  "scope":"g_profile",
  "type":"access_token",
  "username":"test"
}
```

In the OAuth2 behaviour, when you authenticate, you must provide a list of scopes that you require for the user to use the client. If the authentication is successful, Glewlwyd will check what scopes are available for this user and will send back a sublist of available scopes.

So you can't ask for the complete list of available scopes of a user in the OAuth2 endpoints, but this list is available in the `/api/profile` endpoint when you query it with a session token, not an access token, for securoty reasons, because if you query `/api/profile` with an access token, this means a client can do so without asking you and can get private data of a user it shouldn't be allowed to get.

**Comment by Radiergummi** [comment]
So if I understand you correctly, (ab)using scopes for authorization groups is a bad idea? We have several different permission groups, depending on which the user is in, different application modules will be shown in the frontend. It sounds like we'd rather have a single `app` scope to separate Glewlwyd and app users, then handle everything else on the server application...

**Comment by babelouest** [comment]
I'm not sure I understand your use case but when you say:
> (ab)using scopes for authorization groups is a bad idea?

On the contrary, that's exactly what scopes are for.

You can add as much scopes as you want and set as many scopes as you need for each users to use in as many clients as you need.

For example, you can have scopes `app1`, `app2`, `app3` and use those scopes to specify what users are allowed to access to what app.

**Comment by Radiergummi** [comment]
My use case is basically a platform with three types of users -  `employee`, `store_manager`, `manager` and `admin`. As the names imply, all of these have certain permissions (employees may not view sales statistics, store managers may view them for their store, managers may view stats for all stores, etc.).  
My rough idea was to create scopes for these user types, let users authenticate to Glewlwyd and retrieve their token (containing their scope), work in the app, and have my server API return a 403 if the scope doesn't suffice to do something.  
Since I need a scope on logging in, I thought about creating an additional `login` scope, assign it to all users, and continue as planned. That won't work, however, since I need to send all scopes used later on with the `/api/token` call...

Unless I'd have my backend know about the users and manage their permission groups, so the username in the JWT would be used to enforce access control, thus just leaving out scopes altogether.

**Comment by babelouest** [comment]
The JWT are what you need then.

Instead of the additional scope `login`, you can use the built-in scope `g_profile` and add this scope to all users.
Your app will ask for all scopes at login, then depending on the user authorization, he will have an access_token that will contains only the scope he's authorized.

Then your backend will decode and validate the token given, the token will tell the basic information your backend needs: who is the user requesting data and what his scopes are.

One thing with the `store_manager` scope, by itself, it only means that the user has this scope, but it doesn't tell what store he's related. You can have multiple ways to solve this, like using the `additional_property` or maintaing a list of users and their store in your app backend for example.

**Comment by Radiergummi** [comment]
Aha! That is exactly how I will implement it! You are amazing, really. Thank you Nicolas. If you ever come to Munich, make sure to stop by for `n` beers on me! 😊
