### ISSUE TITLE
Current user profile endpoint lacks scopes

### ISSUE THREAD

**Issue by Radiergummi** [babelouest/glewlwyd#44]
As outlined in the [API docs for `GET /api/profile/`](https://github.com/babelouest/glewlwyd/blob/master/docs/API.md#get-current-profile), the response should include the user's scopes. However they don't currently:

```json
{
    "name": "Test McTest",
    "email": "test@test.com",
    "login": "test",
    "additional_property_value": "bar",
    "additional_property_name": "foo"
}
```

Is this by design? I'd like to avoid parsing the token in the client, if possible.

**Comment by babelouest** [comment]
There is an error in the API documentation, indeed it's by design that you can't have the user's scopes by using the API authenticated by an OAuth2 token.

The goal is to forbid a third-party application to access an information he shouldn't have: I don't want my picture of cat manager application to know that I can also access the secret application to launch space rockets.

For a user to be able to get all his scopes, he needs to access the API `/api/profile` with a session token, by using the `app/profile.html` for example.

I'll update the API documentation about that, thanks.

**Comment by Radiergummi** [comment]
Thank you for the clarification, that makes sense. Nevertheless, would it be possible to include the granted scopes in the `api/token` response? Considering it includes the expiration already, that would be helpful: If I tried to obtain a token for some specific scopes and I do receive a token, but not for all scopes I need, I could throw an exception right there.

**Comment by babelouest** [comment]
I understand you need the scopes returned by Glewlwyd in your web client application.

I see 2 ways to fix your problem:
1- you can make an APIs in your application that will return the scopes. i.e. you request scopes `scope1` and `scope2` in glewlwyd, then glewlwyd authenticates the user with `scope1` only. Then if he accesses the API `/api/scopes`, the API can return
```javascript
["scope1"]
```

2- You can decode the `access_token` generated. Since it's a JWT, you have the payload that contains the scopes associated with this token. As explained in the [documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#resource-server-authorization-usage-and-access-tokens)
The token is a 3 base64 strings separated by a dot `.`. The first string is the header, the second string is the payload and the third is the signature. If you base64 decode the second string, you get the payload in a json stringifed, like this:
```javascript
{
  "expires_in": 3600,
  "iat": 1484278795,
  "salt": "abcd1234",
  "scope": "scope1",
  "type": "access_token",
  "username": "admin"
}
```
So you can parse this string in JSON and access the property `"scope"`.

**Comment by Radiergummi** [comment]
Well, yes, solution 1 is essentially what I would like to see included in Glewlwyd, however I understand if you consider this out of, er, scope for it. My general thought was to have application logic separated from the token content and structure - while the scopes field in the token payload might change, the API response doesn't have to.  
I'll go with parsing the token then. Thank you!

**Comment by babelouest** [comment]
As I think of it, I can also modify `/api/profile` to return the list of scopes included in the given token. That would fix your problem without leaking data to unworthy applications.

**Comment by babelouest** [comment]
@Radiergummi , can you try the last commit and tell me if this works as you would like it to?

**Comment by Radiergummi** [comment]
@babelouest That looks exactly as I wanted it to, thank you!
