### ISSUE TITLE
webapp: can`t edit users/clients parameters

### ISSUE THREAD

**Issue by yandoogle** [babelouest/glewlwyd#59]
Hello, Nicolas!

Apparently in the webapp there is a problem with editing properties in the specific data format section. Error occurs when adding new property - "Error while updating module".

Also, I did`t see the new custom properties in the user/client properties db tables. 
Checked by default admin user with g_admin/g_profile scope enabled.

What can be wrong?

**Comment by babelouest** [comment]
The documentation about new parameters isn't written yet.
You need to add the parameter in the module settings.
Then you must edit the file `config.json`, there are 2 sections `user` and `client`. There, you need to add your new parameters with the correct settings.

Concerning the error message at the beginning, if you know how to use the JavaScript console, check if you have error messages, otherwise I'll try to see that later today.

Thanks for reporting!

**Comment by babelouest** [comment]
I answer my own answer, I see the problem with adding new properties in the data format section. I'm gonna look into it.

**Comment by babelouest** [comment]
That's a nasty bug!
When you update the user backend module, it disables the module, then enables it again to update the new configuration.
Except that after disabling the module, the connected user isn't available anymore because the backend module where the admin user is stored is disabled...
You need to restart glewlwyd to enable again the module...
I need a better way to update module settings then!

**Comment by yandoogle** [comment]
Seems the same kind of problem exists at "Authentication schemes modules" dialog. 
Than we change something at existing schemes and trying to save we will get the same error popup.  On server log an error occurs: Glewlwyd ERROR: callback_glewlwyd_user_auth - Error user_session_update (4). 
The following authentication attempts fail until server restart.

**Comment by babelouest** [comment]
I applied the fix to all modules updates so it should be fixed for schemes too.

**Comment by yandoogle** [comment]
Sorry, I forgot to copy the new webapp directory. Now it works as it should!
Thanks.
