### ISSUE TITLE
Let's Encrypt TLS Certificate usage in glewlwyd

### ISSUE THREAD

**Issue by aviezab** [babelouest/glewlwyd#61]
Hello Nico,
I am using let's encrypt TLS from certbot, and this is the conf I wrote in `glewlwyd.conf` I use:
```
# TLS/SSL configuration values
use_secure_connection=true
secure_connection_key_file="/etc/letsencrypt/live/domain/privkey.pem"
secure_connection_pem_file="/etc/letsencrypt/live/domain/cert.pem"
secure_connection_ca_file="/etc/letsencrypt/live/domain/chain.pem"
```
The web and API is running well using browser:
![image](https://user-images.githubusercontent.com/34294278/62679237-15bb8580-b9de-11e9-8c84-b0dc694e8811.png)

but it doesn't work well with CURL, Insomnia or Postman alike:
![image](https://user-images.githubusercontent.com/34294278/62679380-78ad1c80-b9de-11e9-80ed-defef43dcd12.png)

![image](https://user-images.githubusercontent.com/34294278/62679444-b1e58c80-b9de-11e9-8a1b-2503ebe38826.png)

I tried to extract the CA cert of the server:
![image](https://user-images.githubusercontent.com/34294278/62679563-130d6000-b9df-11e9-8aca-4ecaa9026562.png)

Thanks before Nico..

**Comment by babelouest** [comment]
Hello @aviezab ,

As for now, you can't use letsencrypt's chain or fullchain certificate in Glewlwyd configuration, only the key and the certificate files to use the secure connection.

The config parameter `secure_connection_ca_file` is designed to get the [Certificate of Authorithy](https://en.wikipedia.org/wiki/Certificate_authority) file, assuming that there will be a client certificate authentication scheme one day. You should leave it empty for the moment.

So to answer your question, you won't be able to use curl or non-browser clients to access glewlwyd directly.

The solution I use myself is to run Glewlwyd behind a reverse proxy, and the proxy adds the TLS layer with a more flexible configuration. Personnaly I think the proxy solution is better because it adds a layer of security and flexibility (certificates, logs, load-balancing, etc.).

Here is an example of a proxy configuration with apache.
Glewlwyd runs on the same host in http mode (non-secure), listening on port 4593, apache redirects all https connections to the virtual host `glewlwyd.tld` to the glewlwyd process:

```
<VirtualHost *:443>
    ServerName glewlwyd.tld
    ServerAlias glewlwyd.tld
    ErrorLog /var/log/apache/glewlwyd.tld/error.log
    CustomLog /var/log/apache/glewlwyd.tld/requests.log combined
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/glewlwyd.tld/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/glewlwyd.tld/key.pem
    SSLCertificateChainFile /etc/letsencrypt/live/glewlwyd.tld/fullchain.pem

    ProxyPass "/" "http://localhost:4593/"
</VirtualHost>
```

**Comment by aviezab** [comment]
@babelouest Before I used the TLS in Glewlwyd, I have tried reverse proxy with NGINX but there is some weird symptoms. I assume because Glewlwyd runs 2 applications (C and JS) together.
If I hit routes from C API, glewlwyd returns well as it expected to be. But, for website is not running well, it said the TLS certificate is wrong.

After that, I tried to deploy Glewlwyd with it's TLS feature and made this issue.
I will try the next step, removing `secure_connection_ca_file` and using Apache instead of NGINX.
Thanks!

**Comment by babelouest** [comment]
Let me know how it goes then.

I don't know what "weird symptoms" you had with nginx but I assume it's not Glewlwyd related, more certainly a problem with nginx configuration. I had several feedbacks of glewlwyd users who used it behind nginx without problems, and I use it with apache mod_proxy for a few years now without any issue.

**Comment by aviezab** [comment]
@babelouest Oh I see..
I will try several configs available.

For this issue:

> So to answer your question, you won't be able to use curl or non-browser clients to access glewlwyd directly.

We can use chrome extension "Restlet Client" to test the API via browser.
Thanks Nico

**Comment by babelouest** [comment]
>  I will try several configs available.

I'll close this issue then, feel free to open a new issue if you need to.

> We can use chrome extension "Restlet Client" to test the API via browser.

Restlet Client probably uses Chrome's HTTP engine to send HTTP requests.
