### ISSUE TITLE
Could you update docker image (2.0.0 is from 11/3/2019)?

### ISSUE THREAD

**Issue by rurus9** [babelouest/glewlwyd#73]
I use docker image from babelouest/glewlwyd (tag:latest) and I have few issues, but docker image is from 11/3/2019 for 2.0.0 version, and there is over 200 commits in github repo since, maybe these issues are solved but we need newer docker image?

**Comment by babelouest** [comment]
Hello,

The official docker image follows the official release sequence, since there is no new official release since 2.0.0, that's why the docker image hasn't changed.

But I'd preferred you open issues in GitHub for the few issues you have, because I'm not even sure that the commit since the last release would solve your problems.

**Comment by rurus9** [comment]
OK, I am starting to open issues ;)

**Comment by babelouest** [comment]
Hello @rurus9 ,

If you don't want to wait for the next docker official image release, you can build your own docker image as explained in the [install documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#docker-image-builder).

**Comment by rurus9** [comment]
WOW, I built today and it's working!
Thank you.
