### ISSUE TITLE
"Authorization types" in client configuration are not checked

### ISSUE THREAD

**Issue by rurus9** [babelouest/glewlwyd#78]
**Describe the issue**
I use docker image: babelouest/glewlwyd:latest (from 11/3/2019, digest 9347e5910a70) for deployment Glewlwyd2.0.0 in Kubernetes.
I have configured client without any "Authorization types" in client account configuration, and I can still obtain access token for this client with Client Creditentials flow.
I checked - no matter what you set in "Authorization types" in client account (set nothing, 'none', 'something,without,sense' - it is possible with clients in LDAP;) - you cal always get access token in client_creditential flow (i didn't check other flows).

**To Reproduce**
Configure client without any "Authorization types" and try to get access token in Client Creditentials flow.

**Expected behavior**
You can obtain access token in Client Creditentials flow only for client with configured "client" in "Authorization types".

**System (please complete the following information):**
 - OS/Environment [Debian]
 - Browser used [Mozilla Firefox 68.3.0esr]
 - Glewlwyd Version [2.0.0 - docker from babelouest/glewlwyd:latest (from 11/3/2019, digest 9347e5910a70)]

**Comment by babelouest** [comment]
Hello @rurus9 ,

Indeed there was some problems with the auth types with the clients, thanks for reporting!

Fixed in https://github.com/babelouest/glewlwyd/commit/9b3e543d2a94620e86a374e3c0fd25cffcd1de72

There was also a problem in the UI because the config.json.sample file did not have the proper auth_type for `client_credentials`, you should update your config.json file with the following change:
https://github.com/babelouest/glewlwyd/blob/master/webapp/config.json.sample#L126

```diff
< "listElements": ["code","token","id_token","password","none","client","refresh_token","delete_token"]
> "listElements": ["code","token","id_token","password","none","client_credentials","refresh_token","delete_token"]
```

Fixed in https://github.com/babelouest/glewlwyd/commit/b21a1c0b3ff204d90cdab4e6c10bcd75ffdc2f87
