### ISSUE TITLE
[Issue] OIDC token request from Jenkins fails due to form-decoding edge case

### ISSUE THREAD

**Issue by etuttle** [babelouest/glewlwyd#89]
I started a Jenkins container (v2.190.3), enabled its "OpenId Connect Authentication Plugin" (v 1.7), and configured it to connect to glewlwyd (v2.0.0 and I've compiled recent master too).

The initial redirect, login, and redirect back to Jenkins works.   But when the Jenkins server makes its final authorization_code request to glewlwyd, it gets an error response back and then shows a 400 with a stack trace to the user (see below).

I debugged glewlwyd to discover that Jenkins is sending the appropriate parameters, but the post includes a key with no value.

```
redirect_uri=XXXX&scope&client_id=jenkins&client_secret=XXXX
```

MHD is producing callbacks like:

* redirect_url, XXXX
* scope&client_id, jenkins

I repro'd the problem on MHD master and reported it to the MHD mailing list.  Christian Grothoff agreed it is a bug and made a fix on MHD master.  Today I compiled glewlwyd with MHD master and verified, I can finally do a complete Jenkins login flow! (See https://lists.gnu.org/archive/html/libmicrohttpd/2019-12/msg00017.html)

At the moment the MHD fix (f34781c8) is not in any released version.  I suppose once a release happens, glewlwyd can pull in the new version and this issue will be closed.

```
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
	at com.google.api.client.auth.openidconnect.IdTokenResponse.execute(IdTokenResponse.java:120)
	at org.jenkinsci.plugins.oic.OicSecurityRealm$3.onSuccess(OicSecurityRealm.java:394)
	at org.jenkinsci.plugins.oic.OicSession.doFinishLogin(OicSession.java:110)
	at org.jenkinsci.plugins.oic.OicSecurityRealm.doFinishLogin(OicSecurityRealm.java:657)
```

**Comment by babelouest** [comment]
Hello @etuttle ,

Thanks for reporting the issue, I've seen the conversation on MHD mailing list, but I didn't know it was Glewlwyd related.

As I understand, Glewlwyd has nothing to do because it's fixed in MHD directly. But as I mention in the documentation that [MHD 0.9.38 minimum is required](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#libmicrohttpd-0938-minimum-required), I'll add a warning with your issue when MHD will release this fix in a new version.

We'll let this issue open until then.

I'm wondering why Jenkins is sending an empty scope parameter though. The RFC [doesn't require the scope](https://tools.ietf.org/html/rfc6749#section-4.1.3) during the `authorization_code` process, so even if a scope value was sent by the client during the token request, it would be ignored by Glewlwyd and replaced by the [previously verified scopes](https://github.com/babelouest/glewlwyd/blob/master/src/plugin/protocol_oauth2.c#L1319).
But even if technically it isn't a bug, I'd mention this to the Jenkins team.

**Comment by babelouest** [comment]
Libmicrohttpd 0.9.70 has been released on February 8th with the fix: https://ftp.gnu.org/gnu/libmicrohttpd/

I've updated the documentation: https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#libmicrohttpd-0970-minimum-recommended-in-some-edge-cases
