### ISSUE TITLE
Cannot install on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ShyLionTjmn** [babelouest/glewlwyd#98]
Given install instruction just simply does not get you to installed application.
It fails on ./configure --without-openssl stage

Just tried it on fresh server install Ubuntu 18.04.3 LTS

**Comment by babelouest** [comment]
What is the output of the failing command?

**Comment by ShyLionTjmn** [comment]
I could not get past installing libjwt stage.
First it failed with:
`checking whether to build shared libraries... yes
checking whether to build static libraries... yes
./configure: line 11997: syntax error near unexpected token `OPENSSL,'
./configure: line 11997: `	PKG_CHECK_MODULES(OPENSSL, openssl >= 0.9.8)'
`
After some googling i found that i have to install `pkg-config`

Next it comaplined about gnutls:
`checking pkg-config is at least version 0.9.0... yes
checking for GNUTLS... no
configure: error: Package requirements (gnutls >= 3.5.8) were not met:

No package 'gnutls' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GNUTLS_CFLAGS
and GNUTLS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
`
I tried installing gnutls-bin, but above message remaines.

I also tried to download latest libjwt and compile it, but without success.

**Comment by babelouest** [comment]
I updated the documentation for Ubuntu 18.04: https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#install-glewlwyd-on-ubuntu-1804-lts-bionic

Indeed there were flaws in the procedure because you can't build libjwt with gnutls since gnutls is too old on ubuntu bionic, so you must install with libssl instead, and yes pkg-config is mandatory, that's fixed too.
